---
title: "OUT0007494 - Restauration des données"
author: "Dominique Quatravaux"
output:
  html_document: {}
---

```{r knitr.options, include = FALSE}
knitr::opts_chunk$set(echo=FALSE, include = FALSE, warning=FALSE, message=FALSE)
```

```{r libraries}
library(tidyverse)
library(glue)
library(RSQLite)
library(jsonlite)
library(stringr)
library(lubridate)
library(ggplot2)
library(scales)
```

```{r load.and.classify}
tz <- "Europe/Zurich"

load.sql <- function(gzip_sql_path, sqlite3_db_path) {
    gzip_sql_path <- path.expand(gzip_sql_path)
    if (! file.exists(sqlite3_db_path)) {
        system(paste("./sqliteify.sh ", shQuote(gzip_sql_path),
                     " | sqlite3 ", shQuote(sqlite3_db_path)))
    }
    dbConnect(RSQLite::SQLite(), sqlite3_db_path)  %>% tbl("common")
}

db_7h11 <- load.sql("~/Downloads/transfer_99638_files_7c8eb7a3/mysqldump_cv_20221018_0711.sql.gz", "7h11.db")
db_after_500s <- load.sql("~/Downloads/cv_2022-10-18.sql.zip", "db_after_500s.db")

photo_ts <-
    db_7h11 %>%
    select(sciper, photo_ts) %>%
    collect %>%
    left_join(db_after_500s %>% select(sciper, photo_ts) %>% collect,
              by = c("sciper"),
              suffix=c("_7h11", "_after_500s"))

photo_ts %>% filter(photo_ts_7h11 != photo_ts_after_500s)

load.binlogs <- function(path) {
    tmp_jsonp <- basename(path) %>%
        gsub("\\.gz$", "", .) %>%
        paste(".jsonp", sep = "")
    if (! file.exists(tmp_jsonp)) {
        stopifnot(0 == system(paste(
                           "perl parse-binlogs.pl ", path, "cv",
                           " > ", tmp_jsonp), intern = TRUE))
    }
    stream_in(file(tmp_jsonp))
}

binlogs_dir <- path.expand("~/Downloads/transfer_99638_files_7c8eb7a3")
binlogs <- list.files(path = binlogs_dir, pattern = "mysql-bin.*\\.gz$") %>%
    tibble %>%
    rowwise %>%
    summarise({
        tibble(
            basename = .,
            load.binlogs(paste(binlogs_dir, ., sep="/")))
    }) %>%
    ungroup %>%
    mutate(time = timestamp %>%
               as.integer %>%
               as_datetime %>%
               with_tz(tzone = tz),
           sql_operation = word(sql, 1))

binlogs %>% group_by(hms::round_hms(time, secs = 60)) %>% tally %>% arrange(desc(n))

featurify <- function(binlogs) {
    outage = list(starts = ymd_hms("2022-10-18 08:00:00", tz = tz),
                  ends   = ymd_hms("2022-10-18 10:08:00", tz = tz))
    repair = list(starts = ymd_hms("2022-10-18 11:59:48", tz = tz),
                  ends   = ymd_hms("2022-10-18 12:00:05", tz = tz))

    binlogs %>%
        mutate(
            updates_photo_ts = sql_operation == "update" &
                grepl("photo_ts", sql),
            looks_like_line_3665_damage = startsWith(
                sql, "update common set photo_ext='', photo_ts='' where sciper="),
            time_window = case_when(
                time < outage$starts   ~  "before",
                time < outage$ends     ~  "damage",
                time < repair$starts   ~  "during",
                time < repair$ends     ~  "repair",
                TRUE                   ~  "after"))
}

classify.binlog <- function(binlogs) {
    binlogs %>%
        featurify %>%
        mutate(kind = case_when(
                   sql_operation == "update" ~
                       case_when(
                           looks_like_line_3665_damage & time_window == "damage"
                           ~ "Line 3665 damage",

                           updates_photo_ts & time_window == "repair"
                           ~ "Repair script",

                           TRUE
                           ~ "Other update"),

                   TRUE ~ "Other")) %>%
    pull(kind) %>%
    factor %>%
    fct_relevel("Repair script", after = 1) %>%
    fct_relevel("Other", after = Inf)
}
```

```{r classify.histogram, include = TRUE}
binlogs %>%
    mutate(Kind = classify.binlog(.)) %>%
    ggplot(aes(fill=Kind, x=time)) +
    geom_histogram(binwidth = 15 * 60, position = "stack") +
    ggtitle("Classification of SQL writes in binlog") +
    xlab("Time (CEST)") +
    ylab("Count per 15 minutes") +
    scale_x_datetime(breaks = breaks_width("4 hours"))
```
